// Strings for the auth screens, profiles, the manager summary, admin and demo. Russian, sentence case,
// short, no hyphens or dashes (PHASE_0 §6.12). Keys never repeat a shared key (shared wins in t()).
export const authRu: Record<string, string> = {
  // login
  'login.tabTitle': 'Табельный номер',
  'login.tabHint': 'Введите 4 цифры',
  'login.pinTitle': 'ПИН',
  'login.pinHint': 'Табельный номер {tab}',
  'login.changeTab': 'Изменить номер',
  'login.signIn': 'Войти',
  'login.signingIn': 'Входим…',
  'login.tabSlots': 'Введено цифр: {n} из 4',
  'login.pinDots': 'Введено цифр ПИН: {n} из 4',
  'login.demo': 'Демо аккаунты',
  'login.demo.master': 'Мастер 1001',
  'login.demo.ahmetov': 'Ахметов 2001',
  'login.demo.ivanov': 'Иванов 2002',
  'login.demo.manager': 'Главный механик 3001',

  // onboarding
  'onboarding.title': 'Включите уведомления',
  'onboarding.body': 'Новые наряды приходят со звуком. Аварийные требуют ответа.',
  'onboarding.enable': 'Включить',
  'onboarding.later': 'Позже',
  'onboarding.steps': 'Шаг {n} из {total}',
  'onboarding.denied': 'Уведомления можно включить в настройках телефона',

  // profile
  'profile.title': 'Профиль',
  'profile.eyebrow': '{role} · табельный № {tab}',
  'profile.role.worker': 'Исполнитель',
  'profile.role.master': 'Мастер',
  'profile.role.manager': 'Руководитель',
  'profile.role.admin': 'Администратор',
  'profile.grade': '{specialty}, {grade} разряд',
  'profile.shift.day': 'Дневная смена',
  'profile.shift.night': 'Ночная смена',
  'profile.onShift': 'На смене',
  'profile.onShiftOn': 'Мастер может выдавать вам наряды',
  'profile.onShiftOff': 'Наряды вам сейчас не выдают',
  'profile.onShiftError': 'Не удалось изменить смену',
  'profile.connection': 'Связь',
  'profile.connection.live': 'На связи',
  'profile.connection.connecting': 'Подключение…',
  'profile.connection.offline': 'Нет связи',

  'profile.rating.eyebrow': 'Рейтинг за 30 дней',
  'profile.rating.of': 'из 100',
  'profile.rating.closed': 'Закрыто нарядов: {n}',
  'profile.rating.none': 'Нет закрытых нарядов за 30 дней',
  'profile.rating.noneBody': 'Рейтинг появится после первого закрытого наряда',
  'profile.rating.error': 'Рейтинг не загрузился',
  'profile.rating.q': 'Качество',
  'profile.rating.t': 'В срок',
  'profile.rating.f': 'С первого раза',
  'profile.rating.v': 'Объём',
  'profile.rating.d': 'Дисциплина',
  'profile.rating.noValue': 'нет данных',
  'profile.explain.title': 'Из чего сложился рейтинг',
  'profile.explain.loading': 'ИИ готовит объяснение…',
  'profile.explain.error': 'Объяснение пока недоступно',

  'profile.notifications': 'Уведомления',
  'profile.push': 'Push',
  'profile.pushChecking': 'Проверяем…',
  'profile.token': 'Токен',
  'profile.test': 'Проверить уведомление',
  'profile.testSent': 'Уведомление придёт через 2 с',
  'profile.enable': 'Включить уведомления',
  'profile.openSettings': 'Открыть настройки телефона',
  'profile.telegram': 'Подключить Telegram',
  'profile.telegramSoon': 'Скоро: уведомления в Telegram',
  'profile.telegramNote': 'Бот присылает номер наряда, оборудование и срок, без имён',
  'profile.telegramLinkedNote': 'Наряды приходят и в Telegram',
  'profile.telegramLinked': 'Подключён',
  'profile.telegramRelink': 'Telegram',
  'profile.theme': 'Тема',
  'profile.theme.dark': 'Тёмная',
  'profile.theme.light': 'Светлая',
  'profile.theme.system': 'Как в системе',
  'profile.tools': 'Инструменты',
  'profile.demo': 'Демо',
  'profile.demoHint': 'Сброс и тестовые уведомления',
  'profile.kit': 'Кит интерфейса',
  'profile.account': 'Аккаунт',
  'profile.signOut': 'Выйти',
  'profile.signOutTitle': 'Выйти из аккаунта?',
  'profile.signOutBody': 'Этот телефон перестанет получать ваши наряды.',

  // manager summary
  'manager.title': 'Сводка',
  'manager.eyebrow': 'За 30 дней',
  'manager.inProgress': 'Наряды в работе',
  'manager.overdue': 'Просрочки',
  'manager.reaction': 'Среднее время реакции',
  'manager.execution': 'Среднее время выполнения',
  'manager.downtime': 'Простой оборудования',
  'manager.hours': '{n} ч',
  'manager.noValue': 'нет',
  'manager.topEquipment': 'Топ 5 проблемного оборудования',
  'manager.unplanned.one': '{n} внеплановая остановка',
  'manager.unplanned.few': '{n} внеплановые остановки',
  'manager.unplanned.many': '{n} внеплановых остановок',
  'manager.unitDowntime': 'простой {h} ч',
  'manager.noEquipment': 'Внеплановых остановок не было',
  'manager.bestWorkers': 'Лучшие исполнители',
  'manager.closed': 'закрыто {n}',
  'manager.webNote': 'Полная аналитика в веб панели: отчёты, рейтинг, выводы ИИ.',
  'manager.error': 'Сводка не загрузилась',
  'manager.errorBody': 'Проверьте связь и обновите экран',

  // admin
  'admin.title': 'Администратор',
  'admin.eyebrow': '{name} · табельный № {tab}',
  'admin.headline': 'Администратор работает в веб панели',
  'admin.body': 'Справочники, настройки и журнал ИИ открываются в браузере.',
  'admin.address': 'Адрес панели',
  'admin.addressPending': 'появится после публикации',

  // demo
  'demo.title': 'Демо',
  'demo.eyebrow': 'Сценарий показа',
  'demo.settings': 'Режим показа',
  'demo.mode': 'Демо режим',
  'demo.modeHint': 'Новые наряды помечаются как демо, в сроках есть 1 мин',
  'demo.scale': 'Ускорение времени ×10',
  'demo.scaleHint': 'Только чтобы показать эскалацию. Сценарий идёт без ускорения',
  'demo.saveError': 'Настройка не сохранилась',
  'demo.settingsError': 'Настройки не загрузились',
  'demo.reset': 'Сбросить демо',
  'demo.resetHint': 'Стартовое состояние смены без уведомлений',
  'demo.resetTitle': 'Сбросить демо?',
  'demo.resetBody': 'Все наряды, созданные после загрузки истории, удалятся. Смена вернётся к стартовому состоянию.',
  'demo.resetConfirm': 'Сбросить',
  'demo.resetDone': 'Демо сброшено',
  'demo.tests': 'Проверка уведомлений',
  'demo.testOrder': 'Тест: обычный наряд',
  'demo.testEmergency': 'Тест: аварийный наряд',
  'demo.testsFooter': 'Уведомление придёт через 2 с, можно заблокировать телефон',
  'demo.ai': 'Что видит ИИ',
  'demo.aiHint': 'Обезличенные запросы к ИИ: веб панель › Админ › Что видит ИИ',
};
