// Strings for the master screens. Russian, sentence case, short, no hyphens or dashes (PHASE_0 §6.12).
export const masterRu: Record<string, string> = {
  // shared bits of the master screens
  'master.loadError': 'Не получилось загрузить',
  'master.specialtyGrade': '{specialty} · {grade} разряд',
  'master.groupHeader': '{label} · {count}',

  // (master)/index «Смена»
  'master.shift.title': 'Смена',
  'master.shift.eyebrowDay': 'День · с {from} до {to}',
  'master.shift.eyebrowNight': 'Ночь · с {from} до {to}',
  'master.counter.issued': 'Выдано',
  'master.counter.done': 'Выполнено',
  'master.counter.overdue': 'Просрочено',
  'master.counter.stopped': 'В простое',
  'master.group.free': 'Свободны',
  'master.group.working': 'Работают',
  'master.group.queue': 'В очереди',
  'master.group.off': 'Не на смене',
  'master.workers.empty': 'Исполнителей пока нет',
  'master.workers.emptyBody': 'Список появится, когда исполнители выйдут на смену',
  'master.brigades.title': 'Бригады',
  'master.brigades.show': 'Показать',
  'master.brigades.hide': 'Скрыть',
  'master.brigades.leader': 'Бригадир {name}',
  'master.brigades.counts': 'Свободны {free} · Заняты {busy}',
  'master.brigades.off': 'Не на смене',

  // (master)/board «Доска»
  'master.board.title': 'Доска',
  'master.board.columns': 'Колонки доски',
  'master.board.filters': 'Фильтры доски',
  'master.board.filter.area': 'Участок',
  'master.board.filter.equipment': 'Оборудование',
  'master.board.filter.assignee': 'Исполнитель',
  'master.board.filter.priority': 'Приоритет',
  'master.board.filter.all': 'Все',
  'master.board.filter.value': '{name}: {value}',
  'master.board.filter.reset': '✕ Сбросить',
  'master.board.empty.issued': 'Нет выданных нарядов',
  'master.board.empty.accepted': 'Нет принятых нарядов',
  'master.board.empty.queued': 'Очередь пуста',
  'master.board.empty.in_progress': 'Сейчас никто не работает',
  'master.board.empty.done': 'Выполненных пока нет',
  'master.board.empty.overdue': 'Просрочек нет',
  'master.board.empty.body': 'Наряды появятся здесь сами',
  'master.board.empty.filtered': 'Под фильтры ничего не попало',
  'master.board.empty.resetFilters': 'Сбросить фильтры',

  // worker/[id] sheet
  'master.worker.notFound': 'Исполнитель не найден',
  'master.worker.onShift': 'На смене',
  'master.worker.offShift': 'Не на смене',
  'master.worker.current': 'Сейчас',
  'master.worker.queue': 'Очередь',
  'master.worker.empty': 'Активных нарядов нет',
  'master.worker.emptyBody': 'Наряд можно выдать на вкладке «Выдать»',
  'master.worker.offBody': 'Включите «На смене», чтобы выдавать ему наряды',

  // equipment/[id]
  'master.equipment.eyebrow': '{area} · критичность {criticality}',
  'master.equipment.orders': 'Нарядов',
  'master.equipment.unplanned': 'Внеплановых',
  'master.equipment.downtime': 'Простой',
  'master.equipment.stopped': 'Оборудование остановлено',
  'master.equipment.history': 'История',
  'master.equipment.filterAll': 'Все',
  'master.equipment.filterUnplanned': 'Внеплановые',
  'master.equipment.filterPlanned': 'Плановые',
  'master.equipment.empty': 'Нарядов по этому оборудованию нет',
  'master.equipment.emptyBody': 'История появится после первого наряда',
  'master.equipment.more': 'Показать ещё',
  'master.equipment.notFound': 'Оборудование не найдено',

  // ReassignSheet
  'master.reassign.title': 'Переназначить наряд №{number}',
  'master.reassign.subtitle': '{equipment} · сейчас {name}',
  'master.reassign.tabs': 'Кому передать',
  'master.reassign.tabWorkers': 'Исполнители',
  'master.reassign.tabBrigades': 'Бригады',
  'master.reassign.suggested': 'ИИ рекомендует',
  'master.reassign.onShift': 'На смене',
  'master.reassign.done': 'Передан',
  'master.reassign.currentBrigade': 'Наряд уже у этой бригады',
  'master.reassign.noSuggestions': 'ИИ не нашёл подходящих кандидатов',
  'master.reassign.noWorkers': 'Других исполнителей на смене нет',
  'master.reassign.noBrigades': 'Бригад нет',
};
