// Strings for the close form ('close.') and the AI review screens ('review.').
// Russian, sentence case, short, no hyphens or dashes (PHASE_0 §6.12).
// Shared keys reused as they are: review.score5, review.good, review.improve, review.time, check.*,
// verdict.*, action.close, action.override, action.return, action.resume_rework, event.*, common.no_materials.
export const reviewRu: Record<string, string> = {
  // close form
  'close.title': 'Отчёт о работе',
  'close.works': 'Что сделано',
  'close.worksPlaceholder': 'Опишите выполненные работы',
  'close.worksShort': 'Опишите подробнее: ИИ проверяет полноту отчёта',
  'close.phrase.seal': 'Заменил уплотнение',
  'close.phrase.fasteners': 'Подтянул крепёж',
  'close.phrase.bearing': 'Заменил подшипник',
  'close.phrase.lube': 'Выполнил смазку',
  'close.phrase.clean': 'Очистил узел',
  'close.phrase.load': 'Проверил работу под нагрузкой',
  'close.faultCode': 'Шифр неисправности',
  'close.faultCodeNone': 'Выберите шифр',
  'close.selected': 'выбран',
  'close.group.М': 'Механика',
  'close.group.Э': 'Электрика',
  'close.group.Г': 'Гидравлика',
  'close.group.П': 'Пневматика',
  'close.group.С': 'Смазка',
  'close.norm': 'Норматив {hours}',
  'close.suggested': 'Подсказка при выдаче',
  'close.materials': 'Материалы',
  'close.addMaterial': 'Добавить материал',
  'close.addTypical': 'Добавить обычные для {code}',
  'close.typicalHint': 'Обычно {qty} {unit}, до {max} {unit}',
  'close.overNorm': 'Больше нормы: до {max} {unit}',
  'close.notTypical': 'Не входит в норму для {code}',
  'close.zeroQty': 'Количество 0: строка не попадёт в отчёт',
  'close.noMaterialsHint': 'Работы выполнены без расхода материалов',
  'close.search.placeholder': 'Поиск по названию',
  'close.search.typical': 'Обычно для {code}',
  'close.search.all': 'Все материалы',
  'close.search.empty': 'Ничего не найдено',
  'close.search.added': 'Уже в списке',
  'close.photo': 'Фото после',
  'close.photoPrev': 'Фото прошлой попытки',
  'close.photoAdd': 'Снять фото',
  'close.photoItem': 'Фото после',
  'close.photoPreparing': 'Готовлю фото…',
  'close.photoFailed': 'Фото не загрузилось',
  'close.photoError': 'Не загружено',
  'close.photoPermission': 'Нет доступа к камере. Разрешите его в настройках',
  'close.photoUnknown': 'Не удалось снять фото',
  'close.photoDropped': 'Не загружено фото: {n}. Наряд отправлен без него',
  'close.simulator': 'Симулятор: фото из галереи',
  'close.noPhotoBanner': 'Без фото после ИИ может вернуть наряд',
  'close.noPhoto.title': 'Отправить без фото после?',
  'close.noPhoto.message': 'Для внеплановых работ фото после обязательно. Без него ИИ вернёт наряд на доработку.',
  'close.noPhoto.confirm': 'Отправить без фото',
  'close.comment': 'Комментарий',
  'close.commentPlaceholder': 'Необязательно',
  'close.submit': 'Отправить на проверку',
  'close.sent': 'На проверке ИИ',
  'close.unavailable.title': 'Отчёт уже отправлен',
  'close.unavailable.body': 'Отчёт заполняют, когда наряд в работе',
  'close.openReview': 'Открыть отчёт ИИ',

  // review: waiting
  'review.checking': 'ИИ проверяет наряд',
  'review.checkingBody': 'Обычно это занимает несколько секунд',
  'review.pending.completeness': 'Полнота отчёта',
  'review.pending.photo': 'Фото',
  'review.pending.materials': 'Материалы',
  'review.pending.time': 'Время',
  'review.pending.done': 'Проверено',
  'review.pending.running': 'Проверяю…',
  'review.retry': 'Проверить ещё раз',

  // review: shared pieces
  'review.title': 'Отчёт ИИ',
  'review.outOf': 'из 100',
  'review.points': '{points} из {max}',
  'review.timeOnly': 'Время: {actual}',
  'review.goodCheck': '{title}: без замечаний',
  'review.noRemarks': 'Замечаний нет',
  'review.actor.ai': 'ИИ',

  // review: worker
  'review.waitsMaster': 'Ждёт подтверждения мастера',
  'review.needsRework': 'Нужна доработка',
  'review.closed': 'Наряд закрыт',
  'review.byMaster': 'Оценка мастера. ИИ поставил {score} из 100',
  'review.masterComment': 'Комментарий мастера: {comment}',
  'review.toOrder': 'К наряду',
  'review.done': 'Готово',

  // review: master
  'review.score5Conf': '{score5} из 5 · уверенность {conf}',
  'review.score5NoConf': '{score5} из 5 · без оценки уверенности',
  'review.model': 'Модель',
  'review.latency': '{sec} с',
  'review.summary': 'Вывод ИИ',
  'review.checks': 'Проверки',
  'review.photos': 'Фото до и после',
  'review.before': 'До',
  'review.after': 'После',
  'review.noPhoto': 'Нет фото',
  'review.morePhotos': '+{n}',
  'review.photoN': 'Фото {n} из {total}',
  'review.prevPhoto': 'Предыдущее',
  'review.nextPhoto': 'Следующее',
  'review.materials': 'Материалы и норма',
  'review.qty': '{qty} {unit}',
  'review.normUpTo': 'Норма до {max} {unit}',
  'review.overNorm': 'Перерасход: норма до {max} {unit}',
  'review.notTypical': 'Нет в норме для {code}',
  'review.noNorm': 'Норма не задана',
  'review.works': 'Работы',
  'review.worksDone': 'Что сделано',
  'review.worksEmpty': 'Не заполнено',
  'review.faultCode': 'Шифр',
  'review.faultCodeEmpty': 'Не указан',
  'review.timeRow': 'Время',
  'review.downtimeRow': 'Простой оборудования',
  'review.commentRow': 'Комментарий исполнителя',
  'review.timeline': 'Ход работ',
  'review.final': 'Итог мастера',
  'review.aiWas': 'ИИ: {score} из 100, {verdict}',
  'review.assignee': 'Исполнитель {name}',

  // review: master sheets
  'review.override.score': 'Оценка',
  'review.override.verdict': 'Решение',
  'review.override.comment': 'Комментарий',
  'review.override.commentPlaceholder': 'Почему оценка изменена',
  'review.override.submit': 'Закрыть с этой оценкой',
  'review.return.label': 'Что нужно доработать',
  'review.return.placeholder': 'Например: нет фото после ремонта',
  'review.return.required': 'Напишите, что доработать',
  'review.hud.closed': 'Закрыт',
  'review.hud.returned': 'Возвращён на доработку',
  'review.hud.rework': 'Доработка начата',

  // review: states
  'review.error.title': 'Не удалось загрузить наряд',
  'review.error.body': 'Проверьте связь и повторите',
  'review.empty.title': 'Отчёта ИИ пока нет',
  'review.empty.body': 'Он появится после отправки наряда на проверку',
};
