// Generated by scripts/landing-device.mjs. Do not edit by hand.
import masterShift600 from './device/master-shift-600.webp';
import masterShift900 from './device/master-shift-900.webp';
import createAi600 from './device/create-ai-600.webp';
import createAi900 from './device/create-ai-900.webp';
import emergency600 from './device/emergency-600.webp';
import emergency900 from './device/emergency-900.webp';
import workerReport600 from './device/worker-report-600.webp';
import workerReport900 from './device/worker-report-900.webp';
import aiReport600 from './device/ai-report-600.webp';
import aiReport900 from './device/ai-report-900.webp';

/** A real app screen fitted to the 1206 × 2622 display, at two widths for srcset. */
export interface DeviceScreen {
  src: string;
  srcSet: string;
  width: number;
  height: number;
}

export const deviceScreens = {
  masterShift: {
    src: masterShift900,
    srcSet: `${masterShift600} 600w, ${masterShift900} 900w`,
    width: 900,
    height: 1957,
  },
  createAi: {
    src: createAi900,
    srcSet: `${createAi600} 600w, ${createAi900} 900w`,
    width: 900,
    height: 1957,
  },
  emergency: {
    src: emergency900,
    srcSet: `${emergency600} 600w, ${emergency900} 900w`,
    width: 900,
    height: 1957,
  },
  workerReport: {
    src: workerReport900,
    srcSet: `${workerReport600} 600w, ${workerReport900} 900w`,
    width: 900,
    height: 1957,
  },
  aiReport: {
    src: aiReport900,
    srcSet: `${aiReport600} 600w, ${aiReport900} 900w`,
    width: 900,
    height: 1957,
  },
} satisfies Record<string, DeviceScreen>;

export type DeviceScreenName = keyof typeof deviceScreens;
