// Generated by scripts/landing-shots.mjs. Do not edit by hand.
import login from './login.webp';
import masterShift from './master-shift.webp';
import masterBoard from './master-board.webp';
import createAi from './create-ai.webp';
import emergency from './emergency.webp';
import aiReport from './ai-report.webp';

export interface Shot {
  src: string;
  width: number;
  height: number;
}

export const shots = {
  login: { src: login, width: 720, height: 1561 },
  masterShift: { src: masterShift, width: 720, height: 1565 },
  masterBoard: { src: masterBoard, width: 720, height: 1565 },
  createAi: { src: createAi, width: 720, height: 1565 },
  emergency: { src: emergency, width: 720, height: 1561 },
  aiReport: { src: aiReport, width: 720, height: 1561 },
} satisfies Record<string, Shot>;

export type ShotName = keyof typeof shots;
