// Real app screens and the hero wallpaper for the landing page (docs/LANDING.md §3.1), as WebP files in
// src/landing/assets/ plus shots.ts with their sizes (no layout shift). Run once after the screenshots change:
//   node apps/web/scripts/landing-shots.mjs
// Sources: docs/screenshots/presentation/mobile (release build on real data) and packages/design/assets.
import { mkdirSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';

const here = dirname(fileURLToPath(import.meta.url));
const repo = resolve(here, '../../..');
const out = resolve(here, '../src/landing/assets');
mkdirSync(out, { recursive: true });

const SHOT_WIDTH = 720;
const QUALITY = 82;
const MAX_SHOT_BYTES = 120 * 1024;
const MAX_WALLPAPER_BYTES = 250 * 1024;

/** name in the page → screenshot file in docs/screenshots/presentation/mobile */
const shots = {
  login: '01-login.png',
  masterShift: '02-master-shift.png',
  masterBoard: '03-master-board.png',
  createAi: '08-master-create-ai-suggestion.png',
  emergency: '09-worker-emergency.png',
  aiReport: '15-worker-ai-report.png',
};

const kebab = (s) => s.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`);
const sizes = {};

for (const [name, file] of Object.entries(shots)) {
  const src = join(repo, 'docs/screenshots/presentation/mobile', file);
  const dest = join(out, `${kebab(name)}.webp`);
  const info = await sharp(src).resize({ width: SHOT_WIDTH }).webp({ quality: QUALITY }).toFile(dest);
  const bytes = statSync(dest).size;
  if (bytes > MAX_SHOT_BYTES) throw new Error(`${dest} is ${bytes} bytes, over ${MAX_SHOT_BYTES}`);
  sizes[name] = { file: `${kebab(name)}.webp`, width: info.width, height: info.height };
  console.log(`${kebab(name)}.webp ${info.width}×${info.height} ${Math.round(bytes / 1024)} KB`);
}

const wallpaper = join(out, 'wallpaper.webp');
await sharp(join(repo, 'packages/design/assets/wallpaper.jpg')).webp({ quality: 80 }).toFile(wallpaper);
const wallBytes = statSync(wallpaper).size;
if (wallBytes > MAX_WALLPAPER_BYTES) throw new Error(`wallpaper.webp is ${wallBytes} bytes`);
console.log(`wallpaper.webp ${Math.round(wallBytes / 1024)} KB`);

const names = Object.keys(sizes);
const ts = [
  '// Generated by scripts/landing-shots.mjs. Do not edit by hand.',
  ...names.map((n) => `import ${n} from './${sizes[n].file}';`),
  '',
  'export interface Shot {',
  '  src: string;',
  '  width: number;',
  '  height: number;',
  '}',
  '',
  'export const shots = {',
  ...names.map((n) => `  ${n}: { src: ${n}, width: ${sizes[n].width}, height: ${sizes[n].height} },`),
  '} satisfies Record<string, Shot>;',
  '',
  'export type ShotName = keyof typeof shots;',
  '',
].join('\n');
writeFileSync(join(out, 'shots.ts'), ts);
console.log('shots.ts');
