// Screens for the DeviceFrame phone (src/landing/ui/DeviceFrame.tsx): real app screenshots fitted to the 1206 × 2622
// display of the 6.3 inch Pro, with the Dynamic Island the simulator baked in painted over (the frame draws its own,
// crisp at any density), as WebP at two widths for srcset, plus deviceScreens.ts with the URLs and sizes.
//   npm run landing:device   (node apps/web/scripts/landing-device.mjs)
// Sources: docs/screenshots/presentation/mobile (release build on real data). The other landing images come from
// landing-shots.mjs; this script touches only src/landing/assets/device/ and deviceScreens.ts.
import { mkdirSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';

const here = dirname(fileURLToPath(import.meta.url));
const repo = resolve(here, '../../..');
const assets = resolve(here, '../src/landing/assets');
const out = join(assets, 'device');
mkdirSync(out, { recursive: true });

const DISPLAY = { width: 1206, height: 2622 };
const WIDTHS = [600, 900];
const QUALITY = 84;
const MAX_BYTES = 200 * 1024;

/** name in the page → screenshot in docs/screenshots/presentation/mobile */
const screens = {
  masterShift: '02-master-shift.png',
  createAi: '08-master-create-ai-suggestion.png',
  emergency: '09-worker-emergency.png',
  workerReport: '15-worker-ai-report.png',
  aiReport: '28-master-ai-report-sonnet.png',
};

/**
 * Paints over the island the simulator draws into the status bar. It is found as the near black box in the top
 * band; on a black status bar it is invisible and the box fills the whole band, so nothing is painted.
 */
async function withoutIsland(file) {
  const { data, info } = await sharp(file)
    .removeAlpha()
    .raw()
    .toBuffer({ resolveWithObject: true });
  const { width, channels } = info;
  const at = (x, y) => (y * width + x) * channels;
  let minX = Infinity;
  let maxX = -1;
  let minY = Infinity;
  let maxY = -1;
  for (let y = 0; y < 200; y++) {
    for (let x = Math.round(width * 0.3); x < width * 0.7; x++) {
      const i = at(x, y);
      if (data[i] < 10 && data[i + 1] < 10 && data[i + 2] < 10) {
        minX = Math.min(minX, x);
        maxX = Math.max(maxX, x);
        minY = Math.min(minY, y);
        maxY = Math.max(maxY, y);
      }
    }
  }
  const found = maxY > 0 && minY > 8 && maxY - minY < 140;
  if (found) {
    const fill = data.slice(
      at(minX - 16, Math.round((minY + maxY) / 2)),
      at(minX - 16, Math.round((minY + maxY) / 2)) + 3,
    );
    for (let y = minY - 3; y <= maxY + 3; y++) {
      for (let x = minX - 3; x <= maxX + 3; x++) {
        const i = at(x, y);
        data[i] = fill[0];
        data[i + 1] = fill[1];
        data[i + 2] = fill[2];
      }
    }
  }
  return { image: sharp(data, { raw: info }), island: found };
}

const kebab = (s) => s.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`);
const entries = [];

for (const [name, file] of Object.entries(screens)) {
  const { image, island } = await withoutIsland(
    join(repo, 'docs/screenshots/presentation/mobile', file),
  );
  const fitted = await image
    .resize(DISPLAY.width, DISPLAY.height, { fit: 'cover', position: 'top', kernel: 'lanczos3' })
    .png()
    .toBuffer();
  const files = [];
  for (const w of WIDTHS) {
    const dest = join(out, `${kebab(name)}-${w}.webp`);
    const info = await sharp(fitted)
      .resize({ width: w, kernel: 'lanczos3' })
      .webp({ quality: QUALITY, smartSubsample: true })
      .toFile(dest);
    const bytes = statSync(dest).size;
    if (bytes > MAX_BYTES) throw new Error(`${dest} is ${bytes} bytes, over ${MAX_BYTES}`);
    files.push({
      file: `device/${kebab(name)}-${w}.webp`,
      width: info.width,
      height: info.height,
      id: `${name}${w}`,
    });
    console.log(
      `device/${kebab(name)}-${w}.webp ${info.width}×${info.height} ${Math.round(bytes / 1024)} KB${island ? ' (island painted over)' : ''}`,
    );
  }
  entries.push({ name, files });
}

const ts = [
  '// Generated by scripts/landing-device.mjs. Do not edit by hand.',
  ...entries.flatMap((e) => e.files.map((f) => `import ${f.id} from './${f.file}';`)),
  '',
  '/** A real app screen fitted to the 1206 × 2622 display, at two widths for srcset. */',
  'export interface DeviceScreen {',
  '  src: string;',
  '  srcSet: string;',
  '  width: number;',
  '  height: number;',
  '}',
  '',
  'export const deviceScreens = {',
  ...entries.map((e) => {
    const big = e.files[e.files.length - 1];
    const set = e.files.map((f) => `\${${f.id}} ${f.width}w`).join(', ');
    return [
      `  ${e.name}: {`,
      `    src: ${big.id},`,
      `    srcSet: \`${set}\`,`,
      `    width: ${big.width},`,
      `    height: ${big.height},`,
      '  },',
    ].join('\n');
  }),
  '} satisfies Record<string, DeviceScreen>;',
  '',
  'export type DeviceScreenName = keyof typeof deviceScreens;',
  '',
].join('\n');
writeFileSync(join(assets, 'deviceScreens.ts'), ts);
console.log('deviceScreens.ts');
