// Strings of /orders/:id, its dialogs (reassign, priority, cancel, return, override) and the timeline. They follow
// lib/strings.ts (prefix order.) and can move there when the lanes merge; t() below reads them first, then the
// panel and domain dictionaries (action.*, event.*, check.*, review.*, status.*).
import { fill, type I18nParams } from '@rota/shared';
import { t as appT, type Key } from '@/lib/i18n';

export const orderRu = {
  'order.title': 'Наряд №{number}',
  'order.not_found_title': 'Наряд не найден',
  'order.not_found_text': 'Такого наряда нет. Возможно, он удалён после сброса демо.',
  'order.to_board': 'К доске нарядов',

  // sections
  'order.section.card': 'Наряд',
  'order.section.review': 'Проверка ИИ',
  'order.section.works': 'Работы',
  'order.section.materials': 'Материалы и норма',
  'order.section.photos': 'Фото до и после',
  'order.section.timeline': 'Хронология',
  'order.section.actions': 'Действия мастера',

  // info card
  'order.f.area': 'Участок',
  'order.f.equipment': 'Оборудование',
  'order.f.type': 'Тип',
  'order.f.priority': 'Приоритет',
  'order.f.due': 'Срок',
  'order.f.norm': 'Норматив',
  'order.f.assignee': 'Исполнитель',
  'order.f.master': 'Мастер',
  'order.f.issued': 'Выдан',
  'order.f.description': 'Описание',
  'order.f.comment': 'Комментарий мастера',
  'order.f.last_comment': 'Последний комментарий',
  'order.f.suggested_code': 'Предварительный шифр',
  'order.f.repeat': 'Повторный отказ',
  'order.f.stopped': 'Остановка оборудования',
  'order.equipment_history': 'История оборудования ›',
  'order.repeat_link': 'Открыть предыдущий наряд ›',
  'order.repeat_text': 'Тот же узел ремонтировали в последние 7 дней',
  'order.stopped_yes': 'Оборудование остановлено',
  'order.stopped_no': 'Работает',
  'order.brigade_of': '{name} · {brigade}',

  // status card
  'order.status.issued_at': 'Выдан {time}',
  'order.status.since': 'В статусе с {time}',
  'order.status.on_time': 'Выполнен в срок',
  'order.status.late': 'Срок нарушен на {duration}',
  'order.status.final': 'Итог: {verdict}, {score}',
  'order.status.downtime': 'Простой по наряду {duration}',
  'order.status.downtime_running': 'В простое {duration}',

  // works
  'order.works.done': 'Выполненные работы',
  'order.works.code': 'Шифр неисправности',
  'order.works.comment': 'Комментарий исполнителя',
  'order.works.time': 'Время работы',
  'order.works.time_norm': '{actual} при нормативе {norm}',
  'order.works.pending': 'Исполнитель ещё не отчитался о работах.',
  'order.works.empty': 'Текст работ не заполнен',
  'order.works.no_code': 'Шифр не указан',

  // materials
  'order.mat.material': 'Материал',
  'order.mat.qty': 'Количество',
  'order.mat.norm': 'Норма до',
  'order.mat.check': 'Оценка',
  'order.mat.ok': 'В норме',
  'order.mat.over': 'Перерасход',
  'order.mat.not_typical': 'Нет в норме {code}',
  'order.mat.no_norm': 'Норма не задана',
  'order.mat.none': 'Без материалов',
  'order.mat.pending': 'Материалы появятся, когда исполнитель завершит работы.',
  'order.mat.norm_for': 'Норма для шифра {code}',

  // photos
  'order.photo.before': 'До',
  'order.photo.after': 'После',
  'order.photo.none_before': 'Фото до нет',
  'order.photo.none_after': 'Фото после нет',
  'order.photo.required_after': 'Для внеплановых работ фото после обязательно',
  'order.photo.camera': 'Камера',
  'order.photo.gallery': 'Галерея',
  'order.photo.open': 'Открыть фото: {kind}, {n} из {total}',
  'order.photo.unavailable': 'Фото недоступно',
  'order.photo.prev': 'Предыдущее фото',
  'order.photo.next': 'Следующее фото',
  'order.photo.title': '{kind} · {n} из {total}',
  'order.photo.alt': '{kind}: {equipment}',

  // review
  'order.review.waiting_title': 'ИИ проверяет наряд',
  'order.review.waiting_text': 'Обычно это занимает несколько секунд. Результат появится здесь сам.',
  'order.review.not_yet': 'Проверка начнётся, когда исполнитель завершит работы.',
  'order.review.out_of': 'из 100',
  'order.review.score5_conf': '{score5} из 5 · уверенность {conf}',
  'order.review.score5': '{score5} из 5',
  'order.review.needs_master': 'Нужна проверка мастером',
  'order.review.points': '{points} из {max}',
  'order.review.summary': 'Вывод ИИ',
  'order.review.meta_model': 'Модель {model}',
  'order.review.meta_rules': 'Проверка только по правилам',
  'order.review.meta_latency': '{sec} с',
  'order.review.meta_attempt': 'Попытка {n}',
  'order.review.master': 'Решение мастера',
  'order.review.master_line': '{verdict}, {score}',
  'order.review.previous': 'Предыдущие попытки',
  'order.review.prev_line': 'Попытка {n}: {verdict}, {score}',
  'order.review.checks': 'Проверки',

  // actions
  'order.action.close_rated': 'Закрыть с оценкой',
  'order.actions.none': 'Сейчас действий для мастера нет.',
  'order.actions.watch': 'Решения по наряду принимает мастер.',
  'order.done.priority': 'Приоритет: {priority}',
  'order.done.justified': 'Отказ признан обоснованным',
  'order.done.reassigned': 'Передан: {name}',

  // dialogs
  'order.dialog.close': 'Закрыть окно',
  'order.dialog.keep': 'Отмена',
  'order.return.title': 'Вернуть на доработку',
  'order.return.label': 'Что доработать',
  'order.return.placeholder': 'Например: переснимите узел после очистки',
  'order.return.hint': 'Исполнитель получит уведомление с этой причиной, срок продлится.',
  'order.return.need': 'Напишите, что доработать',
  'order.override.title': 'Изменить оценку',
  'order.override.title_none': 'Закрыть с оценкой',
  'order.override.ai': 'ИИ: {verdict}, {score}',
  'order.override.ai_none': 'Отчёта ИИ нет: укажите итог сами',
  'order.override.score': 'Оценка от 0 до 100',
  'order.override.verdict': 'Итог',
  'order.override.comment': 'Комментарий',
  'order.override.comment_placeholder': 'Почему оценка изменена',
  'order.override.submit': 'Закрыть с этой оценкой',
  'order.override.bad_score': 'Оценка от 0 до 100',
  'order.cancel.title': 'Отменить наряд №{number}?',
  'order.cancel.label': 'Причина отмены',
  'order.cancel.placeholder': 'Например: заявка дублирует другой наряд',
  'order.cancel.hint': 'Исполнитель получит уведомление. Отменённый наряд вернуть нельзя.',
  'order.cancel.need': 'Укажите причину отмены',
  'order.cancel.keep': 'Не отменять',
  'order.priority.title': 'Приоритет наряда №{number}',
  'order.priority.current': 'Сейчас',
  'order.priority.emergency_hint': 'Исполнитель получит аварийное уведомление с сиреной.',
  'order.reassign.title': 'Переназначить наряд №{number}',
  'order.reassign.subtitle': '{equipment} · сейчас {name}',
  'order.reassign.tabs': 'Кому передать',
  'order.reassign.workers': 'Исполнители',
  'order.reassign.brigades': 'Бригады',
  'order.reassign.suggested': 'ИИ рекомендует',
  'order.reassign.on_shift': 'На смене',
  'order.reassign.off_shift': 'Не на смене',
  'order.reassign.show_off': 'Показать не на смене · {count}',
  'order.reassign.hide_off': 'Скрыть не на смене',
  'order.reassign.no_suggestions': 'ИИ не нашёл подходящих кандидатов.',
  'order.reassign.no_workers': 'Других исполнителей на смене нет.',
  'order.reassign.no_brigades': 'Бригад нет.',
  'order.reassign.current_brigade': 'Наряд уже у этой бригады',
  'order.reassign.leader': 'Бригадир {name}',
  'order.reassign.no_leader': 'Бригадир не назначен',
  'order.reassign.counts': 'Свободны {free} · Заняты {busy}',
  'order.reassign.anyway': 'Всё равно выдать',
  'order.reassign.ai': 'ИИ',
  'order.escalation.title': 'Наряд не принят вовремя',
  'order.escalation.text': 'ИИ предлагает передать его исполнителю {name}.',

  // the PDF of the master report
  'order.pdf.status': 'Статус',
  'order.pdf.downtime': 'Простой по наряду',
  'order.pdf.deadline': 'Соблюдение срока',
  'order.pdf.final': 'Итог мастера',
  'order.pdf.points': 'Баллы',
  'order.pdf.time': 'Время',
  'order.pdf.event': 'Событие',
  'order.pdf.actor': 'Кто',
  'order.pdf.photo_failed': 'Фото не попали в файл: нет доступа к хранилищу',

  // timeline
  'order.actor.ai': 'ИИ',
  'order.ev.assignee': 'Исполнитель {name}',
  'order.ev.brigade': '{name}, {brigade}',
  'order.ev.move': '{from} → {to}',
  'order.ev.verdict': '{verdict}, {score}',
  'order.ev.needs_master': 'Нужна проверка мастером',
  'order.ev.changed': 'Оценка изменена мастером',
  'order.ev.code': 'Шифр {code}',
  'order.ev.attempt': 'Попытка {n}',
  'order.ev.auto_pause': 'Автоматически, ради другого наряда',
  'order.ev.mark_justified': 'Признать обоснованным',
  'order.ev.justified_tag': 'Обоснован',
  'order.ev.empty': 'Событий пока нет.',
} as const satisfies Record<string, string>;

export type OrderKey = keyof typeof orderRu;

export function t(key: OrderKey | Key, params?: I18nParams): string {
  const own = (orderRu as Record<string, string>)[key];
  return own !== undefined ? fill(own, params) : appT(key as Key, params);
}
