// Mobile app chrome strings that are not part of the shared domain dictionary.
// Domain strings (statuses, reasons, errors, templates) come from @rota/shared `ru.ts`.
// No hyphens or dashes in copy; sentence case; short (PHASE_0 §6.12).
export const mobileRu = {
  'app.name': 'Rota',
  'app.slogan': 'Наряд выдан, ИИ на контроле',

  'kit.title': 'Кит',
  'kit.eyebrow': 'ROTA INDUSTRIAL',
  'kit.theme': 'Тема',
  'kit.themeDark': 'Тёмная',
  'kit.themeLight': 'Светлая',
  'kit.themeSystem': 'Как в системе',
  'kit.tokens': 'Цвета',
  'kit.status': 'Статусы',
  'kit.type': 'Шрифты',
  'kit.buttons': 'Кнопки',
  'kit.controls': 'Элементы управления',
  'kit.lists': 'Списки',
  'kit.orders': 'Наряды',
  'kit.ai': 'Проверка ИИ',
  'kit.input': 'Ввод',
  'kit.photos': 'Фото',
  'kit.feedback': 'Сообщения',
  'kit.mascots': 'Маскоты',
  'kit.brand': 'Логотип',
  'kit.hud': 'HUD',
  'kit.showHud': 'Показать HUD',
  'kit.sample.typeSample': 'Наряд выдан, ИИ на контроле',

  'common.next': 'Далее',
  'common.erase': 'Стереть',
  'common.cancel': 'Отмена',
  'common.confirm': 'Подтвердить',
  'common.close': 'Закрыть',
  'common.back': 'Назад',
  'common.save': 'Сохранить',
  'common.later': 'Позже',
  'common.loading': 'Загрузка',
  'common.retry': 'Повторить',
  'common.takePhoto': 'Снять фото',
  'common.addPhoto': 'Добавить фото',
  'common.ai': 'ИИ',

  'tabs.orders': 'Наряды',
  'tabs.closed': 'Закрытые',
  'tabs.profile': 'Профиль',
  'tabs.shift': 'Смена',
  'tabs.board': 'Доска',
  'tabs.issue': 'Выдать',
  'tabs.summary': 'Сводка',

  'notif.channel.orders': 'Наряды',
  'notif.channel.emergency': 'Аварийные наряды',
  'notif.channel.reminders': 'Напоминания и просрочки',
  'notif.action.accept': 'Принять',
  'notif.action.open': 'Открыть',
  'notif.test.order': 'Тест: обычный наряд',
  'notif.test.emergency': 'Тест: аварийный наряд',
  'notif.test.orderTitle': 'Новый наряд №147',
  'notif.test.orderBody': 'Новый наряд №147. Конвейер К-1, Участок дробления. Срок до 14:30. Приоритет: высокий.',
  'notif.test.emergencyTitle': 'Аварийный наряд №148',
  'notif.test.emergencyBody': 'АВАРИЙНЫЙ наряд №148. Насос НШ-32 маслостанции, Участок обогащения. Требует ответа.',
  'notif.pushNotReady': 'Push пока не настроен',
  'notif.pushReady': 'Push включён',
  'notif.pushDenied': 'Уведомления выключены',
} as const;

export type MobileStringKey = keyof typeof mobileRu;
