// Mobile app chrome strings that are not part of the shared domain dictionary.
// Domain strings (statuses, reasons, errors, templates) and common.* basics come from @rota/shared `ru.ts`,
// which t() checks first: never repeat a shared key here.
// No hyphens or dashes in copy; sentence case; short (PHASE_0 §6.12).
export const mobileRu = {
  'kit.title': 'Кит',
  'kit.eyebrow': 'ROTA INDUSTRIAL',
  'kit.theme': 'Тема',
  'kit.themeDark': 'Тёмная',
  'kit.themeLight': 'Светлая',
  'kit.themeSystem': 'Как в системе',
  'kit.tokens': 'Цвета',
  'kit.status': 'Статусы',
  'kit.type': 'Шрифты',
  'kit.buttons': 'Кнопки',
  'kit.controls': 'Элементы управления',
  'kit.lists': 'Списки',
  'kit.orders': 'Наряды',
  'kit.ai': 'Проверка ИИ',
  'kit.input': 'Ввод',
  'kit.photos': 'Фото',
  'kit.feedback': 'Сообщения',
  'kit.mascots': 'Маскоты',
  'kit.brand': 'Логотип',
  'kit.hud': 'HUD',
  'kit.showHud': 'Показать HUD',
  'kit.sample.typeSample': 'Наряд выдан, ИИ на контроле',

  'common.next': 'Далее',
  'common.erase': 'Стереть',
  'common.close': 'Закрыть',
  'common.later': 'Позже',
  'common.takePhoto': 'Снять фото',
  'common.addPhoto': 'Добавить фото',
  'common.ai': 'ИИ',

  'notFound.title': 'Такой страницы нет',
  'notFound.body': 'Ссылка устарела или набрана с ошибкой',
  'notFound.home': 'На главную',

  'tabs.orders': 'Наряды',
  'tabs.closed': 'Закрытые',
  'tabs.profile': 'Профиль',
  'tabs.shift': 'Смена',
  'tabs.board': 'Доска',
  'tabs.issue': 'Выдать',
  'tabs.summary': 'Сводка',

  'confirm.pauseAndStart': 'Приостановить и начать',
  'confirm.issueAnyway': 'Всё равно выдать',
  'confirm.reassignAnyway': 'Всё равно передать',
  'hud.done': 'Готово',
  'hud.offline': 'Нет связи',
  'hud.open': 'Открыть',
  'order.badge.rejected': 'Отклонён: {reason}',
  'order.badge.paused': 'Пауза: {reason}',
  'order.badge.rework': 'Доработка',
  'order.badge.aiReview': 'Проверка ИИ',
  'order.badge.waitsMaster': 'Ждёт подтверждения',
  'order.badge.overdue': 'Просрочен',
  'order.due': 'до {time}',
  'order.lateShort': '−{duration}',

  'notif.channel.orders': 'Наряды',
  'notif.channel.emergency': 'Аварийные наряды',
  'notif.channel.reminders': 'Напоминания и просрочки',
  'notif.action.accept': 'Принять',
  'notif.action.open': 'Открыть',
  'notif.test.order': 'Тест: обычный наряд',
  'notif.test.emergency': 'Тест: аварийный наряд',
  'notif.test.orderTitle': 'Новый наряд №147',
  'notif.test.orderBody': 'Новый наряд №147. Конвейер К-1, Участок дробления. Срок до 14:30. Приоритет: высокий.',
  'notif.test.emergencyTitle': 'Аварийный наряд №148',
  'notif.test.emergencyBody': 'АВАРИЙНЫЙ наряд №148. Насос НШ-32 маслостанции, Участок обогащения. Требует ответа.',
  'notif.pushNotReady': 'Push пока не настроен',
  'notif.pushReady': 'Push включён',
  'notif.pushDenied': 'Уведомления выключены',
} as const;

export type MobileStringKey = keyof typeof mobileRu;
