// Generated by tools/gen-fixtures.ts from supabase/seed/directories.json. Do not edit by hand.

import type { Area } from '../domain/types';

export const areas: readonly Area[] = [
  {
    id: 1,
    code: 'PIT',
    name: 'Карьер',
    sort: 1,
  },
  {
    id: 2,
    code: 'CRU',
    name: 'Участок дробления',
    sort: 2,
  },
  {
    id: 3,
    code: 'ENR',
    name: 'Участок обогащения',
    sort: 3,
  },
  {
    id: 4,
    code: 'SHP',
    name: 'Участок отгрузки',
    sort: 4,
  },
];
