// Generated by tools/gen-fixtures.ts from supabase/seed/directories.json. Do not edit by hand.

import type { Brigade } from '../domain/types';

export const brigades: readonly Brigade[] = [
  {
    id: 1,
    name: 'Бригада 1',
    leader_id: '00000000-0000-4000-8000-000000002001',
  },
  {
    id: 2,
    name: 'Бригада 2',
    leader_id: '00000000-0000-4000-8000-000000002007',
  },
  {
    id: 3,
    name: 'Бригада 3',
    leader_id: '00000000-0000-4000-8000-000000002011',
  },
];
