// Generated by tools/gen-fixtures.ts from supabase/seed/directories.json. Do not edit by hand.

import type { EquipmentTypeSpecialty } from '../domain/types';

export const equipmentTypeSpecialty: readonly EquipmentTypeSpecialty[] = [
  {
    type: 'буровой станок',
    specialty: 'слесарь',
    label_plural_dat: 'буровым станкам',
  },
  {
    type: 'вентилятор',
    specialty: 'слесарь',
    label_plural_dat: 'вентиляторам',
  },
  {
    type: 'грохот',
    specialty: 'слесарь',
    label_plural_dat: 'грохотам',
  },
  {
    type: 'дробилка',
    specialty: 'слесарь',
    label_plural_dat: 'дробилкам',
  },
  {
    type: 'компрессор',
    specialty: 'слесарь',
    label_plural_dat: 'компрессорам',
  },
  {
    type: 'конвейер',
    specialty: 'слесарь',
    label_plural_dat: 'конвейерам',
  },
  {
    type: 'кран',
    specialty: 'слесарь',
    label_plural_dat: 'кранам',
  },
  {
    type: 'насос',
    specialty: 'слесарь',
    label_plural_dat: 'насосам',
  },
  {
    type: 'погрузчик',
    specialty: 'слесарь',
    label_plural_dat: 'погрузчикам',
  },
  {
    type: 'сушильный барабан',
    specialty: 'слесарь',
    label_plural_dat: 'сушильным барабанам',
  },
  {
    type: 'упаковочная машина',
    specialty: 'электромонтёр',
    label_plural_dat: 'упаковочным машинам',
  },
  {
    type: 'фильтр',
    specialty: 'слесарь',
    label_plural_dat: 'фильтрам',
  },
  {
    type: 'циклон',
    specialty: 'сварщик',
    label_plural_dat: 'циклонам',
  },
  {
    type: 'экскаватор',
    specialty: 'слесарь',
    label_plural_dat: 'экскаваторам',
  },
];
