// Generated by tools/gen-fixtures.ts from supabase/seed/directories.json. Do not edit by hand.

import type { FaultCode } from '../domain/types';

export const faultCodes: readonly FaultCode[] = [
  {
    code: 'Г-01',
    grp: 'Г',
    name: 'Течь масла, повреждение РВД',
    specialty: 'слесарь',
  },
  {
    code: 'Г-02',
    grp: 'Г',
    name: 'Отказ гидронасоса',
    specialty: 'слесарь',
  },
  {
    code: 'Г-03',
    grp: 'Г',
    name: 'Неисправность гидроцилиндра',
    specialty: 'слесарь',
  },
  {
    code: 'М-01',
    grp: 'М',
    name: 'Износ футеровки или брони',
    specialty: 'слесарь',
  },
  {
    code: 'М-02',
    grp: 'М',
    name: 'Подшипник: перегрев, шум, разрушение',
    specialty: 'слесарь',
  },
  {
    code: 'М-03',
    grp: 'М',
    name: 'Повреждение конвейерной ленты',
    specialty: 'слесарь',
  },
  {
    code: 'М-04',
    grp: 'М',
    name: 'Вибрация, нарушение соосности',
    specialty: 'слесарь',
  },
  {
    code: 'М-05',
    grp: 'М',
    name: 'Износ редуктора или зубчатой передачи',
    specialty: 'слесарь',
  },
  {
    code: 'М-06',
    grp: 'М',
    name: 'Трещина металлоконструкции, ослабление крепежа',
    specialty: 'сварщик',
  },
  {
    code: 'М-07',
    grp: 'М',
    name: 'Износ ролика или барабана конвейера',
    specialty: 'слесарь',
  },
  {
    code: 'П-01',
    grp: 'П',
    name: 'Утечка сжатого воздуха',
    specialty: 'слесарь',
  },
  {
    code: 'П-02',
    grp: 'П',
    name: 'Отказ пневмоклапана или пневмоцилиндра',
    specialty: 'слесарь',
  },
  {
    code: 'С-01',
    grp: 'С',
    name: 'Недостаток смазки',
    specialty: 'смазчик',
  },
  {
    code: 'С-02',
    grp: 'С',
    name: 'Загрязнение масла, замена масла',
    specialty: 'смазчик',
  },
  {
    code: 'Э-01',
    grp: 'Э',
    name: 'Отказ электродвигателя',
    specialty: 'электромонтёр',
  },
  {
    code: 'Э-02',
    grp: 'Э',
    name: 'Повреждение кабеля',
    specialty: 'электромонтёр',
  },
  {
    code: 'Э-03',
    grp: 'Э',
    name: 'Неисправность пускателя или автомата',
    specialty: 'электромонтёр',
  },
  {
    code: 'Э-04',
    grp: 'Э',
    name: 'Отказ датчика или концевого выключателя',
    specialty: 'электромонтёр',
  },
  {
    code: 'Э-05',
    grp: 'Э',
    name: 'Срабатывание защиты, перегрев',
    specialty: 'электромонтёр',
  },
  {
    code: 'Э-06',
    grp: 'Э',
    name: 'Неисправность освещения или щита',
    specialty: 'электромонтёр',
  },
];
