// Directory fixtures: the same rows and ids as the database (supabase/seed/directories.json).
// Data files are generated by tools/gen-fixtures.ts; this index, ids.ts and demoState.ts are hand written.

import type { Directories } from '../domain/types';
import { areas } from './areas';
import { brigades } from './brigades';
import { employees } from './employees';
import { equipment } from './equipment';
import { equipmentTypeSpecialty } from './equipmentTypeSpecialty';
import { faultCodes } from './faultCodes';
import { materials } from './materials';
import { problemTemplates } from './problemTemplates';
import { settings } from './settings';
import { workNorms } from './workNorms';

export {
  areas,
  brigades,
  employees,
  equipment,
  equipmentTypeSpecialty,
  faultCodes,
  materials,
  problemTemplates,
  settings,
  workNorms,
};
export { PINS } from './pins';
export { accountEmail, accountPassword, mockEmployeeId } from './ids';

/** A fresh, mutable copy of every directory (MockApi seeds its store from it). */
export function fixtureDirectories(): Directories {
  // JSON round trip: the rows are plain data, and structuredClone is not in every JS engine we target
  const copy = <T>(rows: readonly T[]): T[] => JSON.parse(JSON.stringify(rows)) as T[];
  return {
    areas: copy(areas),
    equipment: copy(equipment),
    brigades: copy(brigades),
    employees: copy(employees),
    fault_codes: copy(faultCodes),
    materials: copy(materials),
    work_norms: copy(workNorms),
    equipment_type_specialty: copy(equipmentTypeSpecialty),
    problem_templates: copy(problemTemplates),
    settings: { ...settings },
  };
}
export {
  DEMO_K2_EQUIPMENT_ID,
  DEMO_ON_SHIFT,
  DEMO_PUMP_EQUIPMENT_ID,
  demoState,
  plannedLabel,
  problemLabel,
  seedChecks,
  seededRandom,
  worksText,
  type DemoState,
  type DemoStateOptions,
} from './demoState';
