// Generated by tools/gen-fixtures.ts from supabase/seed/directories.json. Do not edit by hand.

/** Mock sign in: tab_no → 4 digit PIN (CLAUDE.md §19). The real accounts use password nr_{pin}_kz. */
export const PINS: Readonly<Record<string, string>> = {
  '1001': '1111',
  '1002': '2222',
  '2001': '1234',
  '2002': '1234',
  '2003': '1234',
  '2004': '1234',
  '2005': '1234',
  '2006': '1234',
  '2007': '1234',
  '2008': '1234',
  '2009': '1234',
  '2010': '1234',
  '2011': '1234',
  '2012': '1234',
  '2013': '1234',
  '2014': '1234',
  '2015': '1234',
  '3001': '3333',
  '9001': '9999',
};
