// Generated by tools/gen-fixtures.ts from supabase/seed/directories.json. Do not edit by hand.

import type { Settings } from '../domain/types';

export const settings: Readonly<Settings> = {
  remind_before_min: 30,
  accept_timeout_min: 10,
  accept_timeout_emergency_min: 3,
  overdue_repeat_min: 15,
  manager_overdue_min: 60,
  demo_time_scale: 1,
  demo_mode: true,
  ai_confidence_threshold: 0.6,
  duplicate_hamming_max: 6,
};
