// Generated by tools/gen-fixtures.ts from supabase/seed/directories.json. Do not edit by hand.

import type { WorkNorm } from '../domain/types';

export const workNorms: readonly WorkNorm[] = [
  {
    fault_code: 'Г-01',
    norm_hours: 1.5,
    typical: [
      {
        material_id: 21,
        qty: 2,
        qty_max: 4,
      },
      {
        material_id: 17,
        qty: 3,
        qty_max: 6,
      },
      {
        material_id: 20,
        qty: 1,
        qty_max: 2,
      },
      {
        material_id: 39,
        qty: 1,
        qty_max: 2,
      },
    ],
  },
  {
    fault_code: 'Г-02',
    norm_hours: 4,
    typical: [
      {
        material_id: 17,
        qty: 20,
        qty_max: 40,
      },
      {
        material_id: 23,
        qty: 1,
        qty_max: 2,
      },
      {
        material_id: 21,
        qty: 4,
        qty_max: 8,
      },
      {
        material_id: 22,
        qty: 2,
        qty_max: 4,
      },
    ],
  },
  {
    fault_code: 'Г-03',
    norm_hours: 3,
    typical: [
      {
        material_id: 22,
        qty: 2,
        qty_max: 4,
      },
      {
        material_id: 21,
        qty: 4,
        qty_max: 8,
      },
      {
        material_id: 17,
        qty: 5,
        qty_max: 10,
      },
    ],
  },
  {
    fault_code: 'М-01',
    norm_hours: 6,
    typical: [
      {
        material_id: 7,
        qty: 1,
        qty_max: 1,
      },
      {
        material_id: 8,
        qty: 1,
        qty_max: 1,
      },
      {
        material_id: 12,
        qty: 16,
        qty_max: 32,
      },
      {
        material_id: 13,
        qty: 16,
        qty_max: 32,
      },
      {
        material_id: 14,
        qty: 16,
        qty_max: 32,
      },
    ],
  },
  {
    fault_code: 'М-02',
    norm_hours: 3,
    typical: [
      {
        material_id: 1,
        qty: 1,
        qty_max: 2,
      },
      {
        material_id: 2,
        qty: 1,
        qty_max: 2,
      },
      {
        material_id: 3,
        qty: 1,
        qty_max: 2,
      },
      {
        material_id: 4,
        qty: 1,
        qty_max: 2,
      },
      {
        material_id: 18,
        qty: 0.5,
        qty_max: 1,
      },
    ],
  },
  {
    fault_code: 'М-03',
    norm_hours: 4,
    typical: [
      {
        material_id: 5,
        qty: 10,
        qty_max: 30,
      },
      {
        material_id: 39,
        qty: 1,
        qty_max: 2,
      },
    ],
  },
  {
    fault_code: 'М-04',
    norm_hours: 2.5,
    typical: [
      {
        material_id: 10,
        qty: 1,
        qty_max: 1,
      },
      {
        material_id: 12,
        qty: 4,
        qty_max: 8,
      },
      {
        material_id: 13,
        qty: 4,
        qty_max: 8,
      },
      {
        material_id: 14,
        qty: 4,
        qty_max: 8,
      },
    ],
  },
  {
    fault_code: 'М-05',
    norm_hours: 5,
    typical: [
      {
        material_id: 9,
        qty: 1,
        qty_max: 2,
      },
      {
        material_id: 16,
        qty: 20,
        qty_max: 40,
      },
      {
        material_id: 22,
        qty: 2,
        qty_max: 4,
      },
    ],
  },
  {
    fault_code: 'М-06',
    norm_hours: 2,
    typical: [
      {
        material_id: 15,
        qty: 3,
        qty_max: 6,
      },
      {
        material_id: 12,
        qty: 4,
        qty_max: 8,
      },
      {
        material_id: 13,
        qty: 4,
        qty_max: 8,
      },
    ],
  },
  {
    fault_code: 'М-07',
    norm_hours: 1.5,
    typical: [
      {
        material_id: 6,
        qty: 2,
        qty_max: 4,
      },
      {
        material_id: 18,
        qty: 0.3,
        qty_max: 0.6,
      },
    ],
  },
  {
    fault_code: 'П-01',
    norm_hours: 1,
    typical: [
      {
        material_id: 37,
        qty: 2,
        qty_max: 4,
      },
      {
        material_id: 36,
        qty: 3,
        qty_max: 6,
      },
      {
        material_id: 40,
        qty: 1,
        qty_max: 2,
      },
    ],
  },
  {
    fault_code: 'П-02',
    norm_hours: 1.5,
    typical: [
      {
        material_id: 35,
        qty: 1,
        qty_max: 1,
      },
      {
        material_id: 37,
        qty: 2,
        qty_max: 4,
      },
    ],
  },
  {
    fault_code: 'С-01',
    norm_hours: 0.5,
    typical: [
      {
        material_id: 18,
        qty: 0.8,
        qty_max: 2,
      },
    ],
  },
  {
    fault_code: 'С-02',
    norm_hours: 1.5,
    typical: [
      {
        material_id: 16,
        qty: 20,
        qty_max: 40,
      },
      {
        material_id: 23,
        qty: 1,
        qty_max: 2,
      },
    ],
  },
  {
    fault_code: 'Э-01',
    norm_hours: 4,
    typical: [
      {
        material_id: 25,
        qty: 1,
        qty_max: 1,
      },
      {
        material_id: 27,
        qty: 5,
        qty_max: 10,
      },
      {
        material_id: 33,
        qty: 1,
        qty_max: 2,
      },
    ],
  },
  {
    fault_code: 'Э-02',
    norm_hours: 2,
    typical: [
      {
        material_id: 26,
        qty: 15,
        qty_max: 40,
      },
      {
        material_id: 33,
        qty: 2,
        qty_max: 4,
      },
    ],
  },
  {
    fault_code: 'Э-03',
    norm_hours: 1,
    typical: [
      {
        material_id: 29,
        qty: 1,
        qty_max: 1,
      },
      {
        material_id: 28,
        qty: 1,
        qty_max: 1,
      },
    ],
  },
  {
    fault_code: 'Э-04',
    norm_hours: 1,
    typical: [
      {
        material_id: 30,
        qty: 1,
        qty_max: 2,
      },
      {
        material_id: 31,
        qty: 1,
        qty_max: 2,
      },
    ],
  },
  {
    fault_code: 'Э-05',
    norm_hours: 1.5,
    typical: [
      {
        material_id: 34,
        qty: 3,
        qty_max: 6,
      },
      {
        material_id: 33,
        qty: 1,
        qty_max: 2,
      },
    ],
  },
  {
    fault_code: 'Э-06',
    norm_hours: 1,
    typical: [
      {
        material_id: 32,
        qty: 4,
        qty_max: 8,
      },
      {
        material_id: 28,
        qty: 1,
        qty_max: 1,
      },
    ],
  },
];
