// Web panel chrome strings. Domain strings (statuses, reasons, verdicts, errors) live in @rota/shared ru.ts; t()
// reads both. Sentence case, short, no emoji, no hyphens or dashes in copy. Add page strings here under the page's
// prefix (shift., board., order., report., rating., analytics., dashboard., equipment., admin., demo.).
export const webRu = {
  // roles
  'role.master': 'Мастер',
  'role.manager': 'Руководитель',
  'role.admin': 'Администратор',
  'role.worker': 'Исполнитель',

  // navigation (sidebar)
  'nav.group.work': 'Работа',
  'nav.group.reports': 'Отчёты',
  'nav.group.admin': 'Администрирование',
  'nav.shift': 'Смена',
  'nav.board': 'Доска нарядов',
  'nav.dashboard': 'Сводка',
  'nav.reports_shift': 'Отчёт смены',
  'nav.reports_rating': 'Рейтинг',
  'nav.analytics': 'Аналитика ИИ',
  'nav.admin_directories': 'Справочники',
  'nav.admin_settings': 'Настройки',
  'nav.admin_ai': 'Что видит ИИ',
  'nav.demo': 'Демо',
  'nav.kit': 'Дизайн кит',
  'nav.version': 'Rota 0.1',

  // page titles (document title and page header)
  'page.login': 'Вход',
  'page.landing': 'Наряд выдан, ИИ на контроле',
  'page.shift': 'Смена',
  'page.board': 'Доска нарядов',
  'page.order': 'Наряд №{number}',
  'page.order_loading': 'Наряд',
  'page.reports_shift': 'Отчёт смены',
  'page.reports_rating': 'Рейтинг исполнителей',
  'page.analytics': 'Аналитика ИИ',
  'page.dashboard': 'Сводка',
  'page.equipment': 'История оборудования',
  'page.admin_directories': 'Справочники',
  'page.admin_settings': 'Настройки',
  'page.admin_ai': 'Что видит ИИ',
  'page.demo': 'Демо',
  'page.kit': 'Дизайн кит',
  'page.not_found': 'Страница не найдена',

  // top bar
  'topbar.theme': 'Тема',
  'topbar.theme_dark': 'Тёмная',
  'topbar.theme_light': 'Светлая',
  'topbar.live': 'В сети',
  'topbar.connecting': 'Подключение',
  'topbar.offline': 'Нет связи',
  'topbar.mode_mock': 'Демо данные',
  'topbar.sign_out': 'Выйти',

  // filter bar (CLAUDE.md §14)
  'filter.label': 'Фильтр отчёта',
  'filter.period': 'Период',
  'filter.preset.shift': 'Смена',
  'filter.preset.day': 'Сутки',
  'filter.preset.week': 'Неделя',
  'filter.preset.month': 'Месяц',
  'filter.preset.custom': 'Период',
  'filter.from': 'С',
  'filter.to': 'По',
  'filter.area': 'Участок',
  'filter.equipment': 'Оборудование',
  'filter.assignee': 'Исполнитель',
  'filter.brigade': 'Бригада',
  'filter.all_areas': 'Все участки',
  'filter.all_equipment': 'Всё оборудование',
  'filter.all_assignees': 'Все исполнители',
  'filter.all_brigades': 'Все бригады',
  'filter.reset': 'Сбросить',

  // login
  'login.title': 'Вход в панель',
  'login.subtitle': 'Табельный номер и ПИН, как в приложении',
  'login.tab_placeholder': 'Например, 1001',
  'login.pin_placeholder': '4 цифры',
  'login.submit': 'Войти',
  'login.submitting': 'Входим',
  'login.demo': 'Демо доступ',
  'login.demo_master': 'Мастер 1001',
  'login.demo_manager': 'Главный механик 3001',
  'login.demo_admin': 'Администратор 9001',
  'login.worker_blocked': 'Исполнители работают в мобильном приложении',
  'login.need_both': 'Введите табельный номер и ПИН',
  'login.mock_note': 'Демо данные в этом браузере',

  // shared page states
  'state.loading': 'Загружаем',
  'state.error_title': 'Не получилось загрузить',
  'state.empty_title': 'Пока пусто',
  'state.placeholder_title': 'Раздел готовится',
  'state.placeholder_text': 'Здесь появятся данные этого раздела.',
  'state.not_found_text': 'Такой страницы нет. Вернитесь на главную.',
  'state.go_home': 'На главную',

  // toasts
  'hud.open': 'Открыть',
  'hud.offline': 'Нет связи. Данные обновятся сами',
  'hud.online': 'Связь восстановлена',

  // admin: directories (/admin/directories)
  'admin.readonly': 'Только просмотр',
  'admin.none': 'нет',
  'admin.dir.tabs': 'Справочник',
  'admin.dir.search': 'Поиск по справочнику',
  'admin.dir.search_placeholder': 'Найти',
  'admin.dir.rows_one': 'запись',
  'admin.dir.rows_few': 'записи',
  'admin.dir.rows_many': 'записей',
  'admin.dir.empty_title': 'Справочник пуст',
  'admin.dir.empty_text': 'Строки появятся, когда справочники загрузят в базу.',
  'admin.dir.no_match_title': 'Ничего не найдено',
  'admin.dir.no_match_text': 'Измените запрос поиска.',
  'admin.dir.tab.areas': 'Участки',
  'admin.dir.tab.equipment': 'Оборудование',
  'admin.dir.tab.brigades': 'Бригады',
  'admin.dir.tab.employees': 'Сотрудники',
  'admin.dir.tab.fault_codes': 'Шифры',
  'admin.dir.tab.materials': 'Материалы',
  'admin.dir.tab.work_norms': 'Нормативы',
  'admin.dir.tab.problem_templates': 'Шаблоны проблем',
  'admin.dir.tab.equipment_type_specialty': 'Специальности',
  'admin.col.code': 'Код',
  'admin.col.name': 'Наименование',
  'admin.col.units': 'Единиц',
  'admin.col.stopped': 'В простое',
  'admin.col.area': 'Участок',
  'admin.col.type': 'Тип',
  'admin.col.criticality': 'Критичность',
  'admin.col.inventory_no': 'Инвентарный №',
  'admin.col.state': 'Состояние',
  'admin.col.leader': 'Бригадир',
  'admin.col.members': 'Состав',
  'admin.col.on_shift': 'На смене',
  'admin.col.tab_no': 'Табельный №',
  'admin.col.employee': 'Сотрудник',
  'admin.col.role': 'Роль',
  'admin.col.specialty': 'Специальность',
  'admin.col.grade': 'Разряд',
  'admin.col.brigade': 'Бригада',
  'admin.col.shift': 'Смена',
  'admin.col.pseudonym': 'Псевдоним',
  'admin.col.telegram': 'Telegram',
  'admin.col.fault_code': 'Шифр',
  'admin.col.group': 'Группа',
  'admin.col.norm': 'Норматив',
  'admin.col.sku': 'Артикул',
  'admin.col.unit': 'Единица',
  'admin.col.cost': 'Цена за единицу, тенге',
  'admin.col.typical': 'Типовые материалы',
  'admin.col.equipment_type': 'Тип оборудования',
  'admin.col.problem': 'Проблема',
  'admin.col.suggested_code': 'Шифр по умолчанию',
  'admin.col.plural': 'В пояснениях ИИ',
  'admin.equipment.stopped': 'Остановлено',
  'admin.equipment.running': 'Работает',
  'admin.employee.on_shift': 'На смене',
  'admin.employee.off_shift': 'Не на смене',
  'admin.telegram.linked': 'Подключён',
  'admin.typical.line': '{name} {qty}, до {max}',
  'admin.group.М': 'Механика',
  'admin.group.Э': 'Электрика',
  'admin.group.Г': 'Гидравлика',
  'admin.group.П': 'Пневматика',
  'admin.group.С': 'Смазка',

  // admin: settings (/admin/settings)
  'admin.settings.eyebrow': 'Контроль сроков и проверка ИИ',
  'admin.settings.watchdog': 'Контроль сроков',
  'admin.settings.watchdog_note': 'ИИ проверяет активные наряды каждые 5 секунд. Новые пороги действуют со следующей проверки.',
  'admin.settings.ai': 'Проверка ИИ',
  'admin.settings.ai_note': 'Правила проверки решают жёсткие нарушения, ИИ добавляет оценку, последнее слово за мастером.',
  'admin.settings.demo': 'Демо',
  'admin.settings.demo_row_hint': 'Переключаются на странице «Демо»',
  'admin.settings.open_demo': 'Открыть «Демо»',
  'admin.settings.on': 'Вкл',
  'admin.settings.off': 'Выкл',
  'admin.settings.scale_note': 'Ускорение ×{scale} включено: все пороги контроля сроков делятся на {scale}.',
  'admin.settings.key.remind_before_min': 'Напоминание до срока',
  'admin.settings.hint.remind_before_min': 'За сколько минут до срока исполнитель получит напоминание',
  'admin.settings.key.accept_timeout_min': 'Время на принятие',
  'admin.settings.hint.accept_timeout_min': 'Если наряд не принят, мастер получит эскалацию с кандидатом на замену',
  'admin.settings.key.accept_timeout_emergency_min': 'Время на принятие аварийного',
  'admin.settings.hint.accept_timeout_emergency_min': 'То же для аварийных нарядов',
  'admin.settings.key.overdue_repeat_min': 'Повтор сообщения о просрочке',
  'admin.settings.hint.overdue_repeat_min': 'Как часто исполнитель и мастер слышат о просроченном наряде',
  'admin.settings.key.manager_overdue_min': 'Длительная просрочка',
  'admin.settings.hint.manager_overdue_min': 'Через сколько минут после срока сообщение получит руководитель',
  'admin.settings.key.ai_confidence_threshold': 'Порог уверенности ИИ',
  'admin.settings.hint.ai_confidence_threshold': 'Ниже порога наряд ждёт проверки мастером',
  'admin.settings.key.duplicate_hamming_max': 'Порог совпадения фото',
  'admin.settings.hint.duplicate_hamming_max': 'Различие отпечатков фото разных нарядов, при котором фото считается повтором. Меньше значит строже',
  'admin.settings.unit.min': 'мин',
  'admin.settings.unit.share': 'доля',
  'admin.settings.unit.bits': 'бит',
  'admin.settings.default': 'По умолчанию {value}',
  'admin.settings.scaled': 'Сейчас {value}',
  'admin.settings.seconds': '{value} с',
  'admin.settings.invalid_int': 'Целое число от {min} до {max}',
  'admin.settings.invalid_share': 'Число от {min} до {max}',
  'admin.settings.dirty': 'Есть несохранённые изменения',
  'admin.settings.discard': 'Отменить изменения',
  'admin.settings.defaults': 'Значения по умолчанию',
  'admin.settings.saving': 'Сохраняем',
  'admin.settings.saved': 'Настройки сохранены',
  'admin.settings.save_error': 'Настройки не сохранились',

  // admin: «Что видит ИИ» (/admin/ai)
  'admin.ai.eyebrow': 'Журнал запросов к ИИ',
  'admin.ai.intro_title': 'Персональные данные не уходят к ИИ',
  'admin.ai.intro_text': 'Перед отправкой шлюз заменяет фамилии, имена, табельные номера и телефоны псевдонимами. Ниже ровно то, что получила и вернула модель.',
  'admin.ai.empty_title': 'Запросов к ИИ пока не было',
  'admin.ai.empty_text': 'Журнал заполнится, когда ИИ проверит первый наряд или напишет сводку смены.',
  'admin.ai.empty_mock': 'В демо данных ИИ работает в браузере и никуда не отправляет запросы. Журнал ведёт рабочая база.',
  'admin.ai.kpi.calls': 'Запросов',
  'admin.ai.kpi.cost': 'Расход, USD',
  'admin.ai.kpi.cost_hint': 'За всё время',
  'admin.ai.kpi.latency': 'Среднее время ответа',
  'admin.ai.no_data': 'нет данных',
  'admin.ai.kpi.errors': 'Ошибки',
  'admin.ai.kpi.errors_hint': 'При ошибке работают правила без ИИ',
  'admin.ai.list': 'Последние запросы',
  'admin.ai.refresh': 'Обновить',
  'admin.ai.filter': 'Назначение',
  'admin.ai.all': 'Все',
  'admin.ai.purpose.verify': 'Проверка наряда',
  'admin.ai.purpose.insights': 'Аналитика',
  'admin.ai.purpose.shift_summary': 'Сводка смены',
  'admin.ai.purpose.explain_rating': 'Пояснение рейтинга',
  'admin.ai.purpose.parse_query': 'Разбор вопроса',
  'admin.ai.purpose.smoke': 'Проверка связи',
  'admin.ai.result.ok': 'Ответ получен',
  'admin.ai.result.error': 'Ошибка',
  'admin.ai.result.pending': 'Нет ответа',
  'admin.ai.seconds': '{value} с',
  'admin.ai.request': 'Запрос',
  'admin.ai.response': 'Ответ',
  'admin.ai.system': 'Системная инструкция',
  'admin.ai.show_system': 'Показать',
  'admin.ai.hide_system': 'Скрыть',
  'admin.ai.message.user': 'Сообщение',
  'admin.ai.message.assistant': 'Ответ модели',
  'admin.ai.image': 'Фото {type} · {size}',
  'admin.ai.kb': '{value} КБ',
  'admin.ai.tokens': 'Токены: {input} на входе, {output} на выходе',
  'admin.ai.no_response': 'Ответа нет: запрос прервался до ответа модели.',
  'admin.ai.error_code': 'Ошибка {code}',
  'admin.ai.select': 'Выберите запрос в списке',
  'admin.ai.pseudonym': 'Псевдоним вместо человека',
  'admin.ai.directory': 'Псевдонимы',
  'admin.ai.directory_note': 'По этой таблице шлюз заменяет людей перед отправкой и возвращает имена в ответе. Сама таблица к ИИ не уходит.',

  // demo (/demo, the same controls as the mobile «Демо» screen)
  'demo.eyebrow': 'Сценарий показа',
  'demo.settings': 'Режим показа',
  'demo.mode': 'Демо режим',
  'demo.mode_hint': 'Новые наряды помечаются как демо, в сроках есть 1 мин',
  'demo.scale': 'Ускорение времени ×10',
  'demo.scale_hint': 'Только чтобы показать эскалацию. Сценарий идёт без ускорения',
  'demo.save_error': 'Настройка не сохранилась',
  'demo.settings_error': 'Настройки не загрузились',
  'demo.reset': 'Сбросить демо',
  'demo.reset_hint': 'Стартовое состояние смены без уведомлений',
  'demo.reset_title': 'Сбросить демо?',
  'demo.reset_body': 'Все наряды, созданные после загрузки истории, удалятся. Смена вернётся к стартовому состоянию.',
  'demo.reset_confirm': 'Сбросить',
  'demo.resetting': 'Сбрасываем',
  'demo.reset_done': 'Демо сброшено',
  'demo.ai': 'Что видит ИИ',
  'demo.ai_hint': 'Обезличенные запросы к ИИ',
  'demo.ai_master_hint': 'Журнал запросов к ИИ открывает администратор',
  'demo.open': 'Открыть',
  'demo.mock_note': 'Демо данные живут в этом браузере, другие устройства их не видят.',
  'demo.state': 'Готовность смены',
  'demo.state_note': 'После сброса на смене 9 человек, свободны Ахметов, Ким и Касымов.',
  'demo.kpi.on_shift': 'На смене',
  'demo.kpi.free': 'Свободны',
  'demo.kpi.working': 'В работе',
  'demo.kpi.queue': 'С очередью',
  'demo.kpi.off': 'Не на смене',
  'demo.free_list': 'Свободны: {names}',
  'demo.nobody_free': 'Свободных нет',
  'demo.script': 'Сценарий',
  'demo.script_note': 'Телефон A мастер 1001, B Ахметов 2001, C Иванов 2002. Время без ускорения.',
  'demo.step.1': 'Мастер: панель смены показывает, кто свободен, занят, в очереди и не на смене.',
  'demo.step.2': 'Мастер: фото течи на насосе НШ-32, аварийный наряд, ИИ предлагает Ахметова, «Выдать».',
  'demo.step.3': 'Ахметов: сирена и красный экран, «Принять», затем «Начать».',
  'demo.step.4': 'Мастер: второй наряд Ахметову со сроком 1 мин, Ахметов ставит его в очередь.',
  'demo.step.5': 'Ахметов: закрывает первый наряд, шифр Г-01, материалы и фото после.',
  'demo.step.6': 'ИИ проверяет наряд, вердикт «Принято», мастер нажимает «Согласен, закрыть».',
  'demo.step.7': 'Иванов: закрывает К-2 без фото и с 6 подшипниками, ИИ возвращает на доработку.',
  'demo.step.8': 'Веб панель: отчёт смены со сводкой ИИ и рейтинг за месяц.',
  'demo.step.9': 'Веб панель: аналитика за 3 месяца и вопрос про участок дробления.',

  // reports: shift report (/reports/shift), shared by the dashboard and analytics
  'report.eyebrow_shift': 'Смена · {shift} · {date} · {hours}',
  'report.eyebrow_range': '{label} · с {from} по {to}',
  'report.export_pdf': 'Скачать PDF',
  'report.export_excel': 'Скачать Excel',
  'report.export_soon': 'Экспорт появится в следующей версии',
  'report.no_data': 'нет данных',
  'report.hours': '{value} ч',
  'report.section.orders': 'Наряды',
  'report.section.time': 'Время и простой',
  'report.kpi.issued': 'Выдано',
  'report.kpi.accepted': 'Принято',
  'report.kpi.done': 'Исполнено',
  'report.kpi.closed': 'Закрыто',
  'report.kpi.overdue': 'Просрочено',
  'report.kpi.rejected': 'Отклонено',
  'report.kpi.rework': 'На доработку',
  'report.kpi.active_hint': 'Активных сейчас: {n}',
  'report.kpi.cancelled_hint': 'Отменено: {n}',
  'report.kpi.reaction': 'Среднее время реакции',
  'report.kpi.reaction_hint': 'От выдачи до принятия',
  'report.kpi.execution': 'Среднее время выполнения',
  'report.kpi.execution_hint': 'От начала до исполнения, без пауз',
  'report.kpi.on_time': 'Выполнено в срок',
  'report.kpi.downtime': 'Простой оборудования',
  'report.kpi.downtime_hint': 'Наряды с остановкой оборудования',
  'report.summary.title': 'Сводка ИИ',
  'report.summary.heading': 'ИИ подведёт итоги смены',
  'report.summary.text':
    'Здесь появятся итоги периода в нескольких предложениях и три рекомендации по этим цифрам. Сводка ИИ будет в следующей версии.',
  'report.summary.loading': 'ИИ читает отчёт',
  'report.summary.loading_text': 'Сводка по цифрам периода появится через несколько секунд',
  'report.summary.refresh': 'Обновить',
  'report.summary.refreshing': 'Обновляем',
  'report.summary.recs': 'Рекомендации на следующую смену',
  'report.summary.meta_llm': 'Модель {model}, {time}',
  'report.summary.meta_model': 'Модель {model}',
  'report.summary.meta_rules': 'Собрано по цифрам отчёта без модели ИИ',
  'report.summary.meta_mock': 'Тестовые данные',
  'report.summary.error': 'Сводку получить не удалось. Цифры отчёта ниже верны.',

  // exports (PDF and Excel of the report pages and the order report)
  'export.busy': 'Готовим файл',
  'export.failed': 'Файл подготовить не удалось. Попробуйте ещё раз.',
  'export.done': 'Файл скачан',
  'export.generated': 'Сформировано {time}',
  'export.page': 'Стр. {n} из {total}',
  'export.footer': 'Rota · Наряд выдан, ИИ на контроле',
  'export.filter': 'Фильтр: {parts}',
  'export.filter_all': 'Все участки, оборудование и исполнители',
  'export.filter.area': 'участок «{name}»',
  'export.filter.equipment': 'оборудование «{name}»',
  'export.filter.assignee': 'исполнитель {name}',
  'export.filter.brigade': '{name}',
  'export.kpi.active_now': 'Активных сейчас',
  'export.kpi.cancelled': 'Отменено',
  'export.kpi.overrides': 'Оценку ИИ изменил мастер',
  'export.unit.min': 'мин',
  'export.unit.h': 'ч',
  'export.col.metric': 'Показатель',
  'export.col.value': 'Значение',
  'export.col.unit': 'Ед.',
  'export.col.verdict': 'Вердикт',
  'export.col.orders': 'Нарядов',
  'export.col.area': 'Участок',
  'export.col.busy_min': 'В работе, мин',
  'export.col.hours': 'Простой, ч',
  'export.col.late_min': 'Просрочка, мин',
  'export.col.note': 'Примечание',
  'export.sheet.summary': 'Сводка',
  'export.sheet.workload': 'Загрузка',
  'export.sheet.downtime': 'Простой',
  'export.sheet.overdue': 'Просрочки',
  'export.sheet.rejects': 'Отказы',
  'export.sheet.verdicts': 'Проверка ИИ',
  'export.sheet.issues': 'Неисправности',
  'export.sheet.equipment': 'Оборудование',
  'export.rating.legend': 'Как считается рейтинг',
  'report.workload.title': 'Загрузка исполнителей',
  'report.workload.worker': 'Исполнитель',
  'report.workload.busy': 'В работе',
  'report.workload.share': 'Загрузка',
  'report.workload.empty': 'За период никто не работал по нарядам',
  'report.downtime.title': 'Простой оборудования',
  'report.downtime.equipment': 'Оборудование',
  'report.downtime.orders': 'Нарядов',
  'report.downtime.hours': 'Простой',
  'report.downtime.empty': 'Оборудование не останавливалось',
  'report.overdue.title': 'Просроченные наряды',
  'report.overdue.number': 'Наряд',
  'report.overdue.equipment': 'Оборудование',
  'report.overdue.assignee': 'Исполнитель',
  'report.overdue.status': 'Статус',
  'report.overdue.due': 'Срок',
  'report.overdue.late': 'Просрочка',
  'report.overdue.empty': 'Просрочек нет',
  'report.rejects.title': 'Отказы и причины',
  'report.rejects.reason': 'Причина',
  'report.rejects.count': 'Отказов',
  'report.rejects.share': 'Доля',
  'report.rejects.no_reason': 'Без причины',
  'report.rejects.empty': 'Отказов не было',
  'report.verdicts.title': 'Проверка ИИ',
  'report.verdicts.overrides': 'Оценку изменил мастер: {n}',
  'report.verdicts.empty': 'ИИ ещё не проверял наряды за период',
  'report.issues.title': 'Частые неисправности',
  'report.issues.code': 'Шифр',
  'report.issues.name': 'Неисправность',
  'report.issues.count': 'Нарядов',
  'report.issues.empty': 'Внеплановых нарядов не было',
  'report.top_equipment.title': 'Чаще всего ломалось',
  'report.top_equipment.count': 'Внеплановых',

  // reports: rating (/reports/rating)
  'rating.tabs': 'Кого показать',
  'rating.tab.workers': 'Исполнители',
  'rating.tab.brigades': 'Бригады',
  'rating.table_title': 'Компоненты рейтинга',
  'rating.col.rank': 'Место',
  'rating.col.worker': 'Исполнитель',
  'rating.col.brigade': 'Бригада',
  'rating.col.closed': 'Закрыто',
  'rating.col.score': 'Рейтинг',
  'rating.q': 'Качество',
  'rating.t': 'В срок',
  'rating.f': 'С первого раза',
  'rating.v': 'Объём',
  'rating.d': 'Дисциплина',
  'rating.chart.title': 'Из чего сложился рейтинг',
  'rating.chart.subtitle': 'Баллы из 100 по компонентам',
  'rating.chart.total': 'Рейтинг',
  'rating.formula':
    'Рейтинг из 100: качество 35%, в срок 25%, с первого раза 20%, объём 10%, дисциплина 10%. Качество, срок и первый раз сглажены по команде, поэтому исполнитель с двумя нарядами не выходит в лидеры.',
  'rating.no_closed': 'нет закрытых нарядов',
  'rating.empty_title': 'Нет закрытых нарядов',
  'rating.empty_text': 'За этот период рейтинг считать не из чего. Выберите период длиннее, например месяц.',

  // dashboard (/dashboard)
  'dashboard.link.report': 'Отчёт смены ›',
  'dashboard.link.analytics': 'Аналитика ИИ ›',
  'dashboard.kpi.in_progress': 'Наряды в работе',
  'dashboard.kpi.in_progress_hint': 'Сейчас, все незакрытые',
  'dashboard.kpi.overdue': 'Просрочено',
  'dashboard.kpi.overdue_hint': 'Сейчас, срок истёк',
  'dashboard.kpi.execution_hint': 'Без пауз',
  'dashboard.kpi.downtime_hint': 'С остановкой оборудования',
  'dashboard.kpi.closed_hint': 'Закрыто {orders}',
  'dashboard.top.title': 'Топ 5 проблемного оборудования',
  'dashboard.top.unplanned': 'Внеплановых',
  'dashboard.top.downtime': 'Простой',
  'dashboard.top.empty': 'Внеплановых отказов за период не было',
  'dashboard.best.title': 'Лучшие исполнители',
  'dashboard.best.all': 'Весь рейтинг ›',
  'dashboard.best.empty': 'Пока нет исполнителей с тремя закрытыми нарядами за период',

  // analytics (/analytics)
  'analytics.ask.label': 'Вопрос к ИИ',
  'analytics.ask.placeholder': 'Спросите, например: покажи проблемы участка дробления за месяц',
  'analytics.ask.submit': 'Спросить',
  'analytics.ask.clear': 'Сбросить вопрос',
  'analytics.ask.hint': 'Назовите участок, период и тему: оборудование, повторные отказы, ППР, ночные смены, исполнители, материалы, рост отказов.',
  'analytics.ask.examples': 'Например',
  'analytics.ask.example_1': 'Покажи проблемы участка дробления за месяц',
  'analytics.ask.example_2': 'Где растёт число отказов за 3 месяца',
  'analytics.ask.example_3': 'Перерасход материалов за месяц',
  'analytics.ask.asking': 'ИИ разбирает вопрос и пишет выводы. Это займёт до 30 секунд.',
  'analytics.scope.question': 'Вопрос понят так',
  'analytics.scope.period_title': 'Выводы за период',
  'analytics.scope.period': 'За {label}',
  'analytics.scope.dates': 'с {from} по {to}',
  'analytics.scope.all_areas': 'Все участки',
  'analytics.scope.source.llm': 'Выводы ИИ',
  'analytics.scope.source.mixed': 'Выводы ИИ и правил',
  'analytics.scope.source.rules': 'Выводы по правилам',
  'analytics.scope.parsed.llm': 'Вопрос разобран ИИ',
  'analytics.scope.parsed.rules': 'Вопрос разобран по ключевым словам',
  'analytics.scope.cached': 'Сохранённый ответ',
  'analytics.loading_title': 'ИИ ищет закономерности',
  'analytics.loading_text': 'Сравниваем отказы, ремонты и расход материалов за период',
  'analytics.empty_title': 'Закономерностей не найдено',
  'analytics.empty_text': 'За этот период отклонений нет. Выберите период длиннее, например месяц.',
  'analytics.cards': 'Выводы',
  'analytics.card.ai': 'ИИ',
  'analytics.severity.critical': 'Критично',
  'analytics.severity.warning': 'Внимание',
  'analytics.severity.info': 'К сведению',
  'analytics.kind.top_areas': 'Участки',
  'analytics.kind.top_equipment': 'Оборудование',
  'analytics.kind.repeat_faults': 'Повторные отказы',
  'analytics.kind.post_ppr': 'После ППР',
  'analytics.kind.time_patterns': 'Время суток',
  'analytics.kind.worker_repeats': 'Исполнитель',
  'analytics.kind.materials': 'Материалы',
  'analytics.kind.trend': 'Тренд',
  'analytics.kind.shift_summary': 'Итоги смены',
  'analytics.kind.weekly_digest': 'Сводка недели',
  'analytics.recommendation': 'Рекомендация',
  'analytics.evidence_count': 'Доказательства · {orders}',
  'analytics.evidence_hide': 'Скрыть доказательства',
  'analytics.evidence.orders': 'Наряды',
  'analytics.evidence.empty': 'Нет связанных нарядов',
  'analytics.evidence.more': 'Показать все {n}',
  'analytics.evidence.less': 'Свернуть',
  'analytics.evidence.missing': 'Ещё {orders} не показаны',
  'analytics.evidence.chart': 'Наряды по неделям',
  'analytics.evidence.chart_hint': 'Только наряды из доказательств',
  'analytics.evidence.unplanned': 'Внеплановые',
  'analytics.evidence.planned': 'Плановые',
  'analytics.evidence.equipment': 'История оборудования ›',
  'analytics.week': 'Неделя с {date}',
  'analytics.total': 'Всего',
  'analytics.stat.unplanned': 'Внеплановых',
  'analytics.stat.downtime_h': 'Простой',
  'analytics.stat.ratio_to_median': 'Выше медианы парка, раз',
  'analytics.stat.count': 'Повторов',
  'analytics.stat.median_days_between': 'Дней между отказами',
  'analytics.stat.workers': 'Исполнителей',
  'analytics.stat.planned': 'ППР',
  'analytics.stat.followed_by_failure': 'Отказ после ППР',
  'analytics.stat.unit_base': 'Отказ в остальное время',
  'analytics.stat.lift': 'Чаще после ППР, раз',
  'analytics.stat.night': 'Ночью',
  'analytics.stat.day': 'Днём',
  'analytics.stat.night_to_day': 'Ночью чаще, раз',
  'analytics.stat.repairs': 'Ремонтов',
  'analytics.stat.repeat_share': 'Повторный отказ',
  'analytics.stat.team_share': 'По команде',
  'analytics.stat.rework_share': 'На доработку',
  'analytics.stat.orders': 'Нарядов',
  'analytics.stat.avg_qty': 'Средний расход',
  'analytics.stat.reference_qty': 'Норма',
  'analytics.stat.ratio': 'Выше нормы, раз',
  'analytics.stat.slope_per_week': 'Рост за неделю',
  'analytics.stat.peak': 'Пик',
  'analytics.stat.peak_value': 'с {from} до {to}',
  'analytics.stat.units': 'Единиц оборудования',
  'analytics.stat.per_unit': 'Отказов на единицу',
  'analytics.chart.codes': 'Частые шифры',
  'analytics.chart.codes_hint': 'Внеплановые отказы по шифру',
  'analytics.chart.night_day': 'Ночью и днём',
  'analytics.chart.night_day_hint': 'Отказы за период',
  'analytics.chart.night': 'Ночью',
  'analytics.chart.day': 'Днём',
  'analytics.chart.repeat': 'Повторный отказ',
  'analytics.chart.repeat_hint': 'Доля ремонтов, после которых отказ повторился за 7 дней',
  'analytics.chart.worker': 'Исполнитель',
  'analytics.chart.team': 'Команда',
  'analytics.chart.ppr': 'Отказ в течение 5 дней',
  'analytics.chart.ppr_hint': 'Доля окон после ППР и в остальное время',
  'analytics.chart.after_ppr': 'После ППР',
  'analytics.chart.other_time': 'В остальное время',
  'analytics.chart.qty': 'Расход на наряд',
  'analytics.chart.actual': 'Факт',
  'analytics.chart.norm': 'Норма',
  'analytics.chart.weeks': 'Отказы по неделям',
  'analytics.chart.weeks_hint': 'Последние 6 полных недель',
  'analytics.chart.week_n': 'Неделя {n}',
  'analytics.chart.value': 'Значение',
} as const satisfies Record<string, string>;

export type WebKey = keyof typeof webRu;
